const basketActionTypes = {
  DİSPLAY_BASKET: "DİSPLAY_BASKET",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",

  CLEAR_BASKET: "CLEAR_BASKET",

  INC_QUANTİTY: "INC_QUANTİTY",
  DEC_QUANTİTY: "DEC_QUANTİTY",
  BASKET_ERROR: "BASKET_ERROR",
  BASKET_LOADING: "BASKET_LOADING",
};

export default basketActionTypes;
